# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install react-scripts
      run: npm install react-scripts@3.4.1 -g --silent
    - name: Test
      run: npm test
    - name: Build
      run: npm run build
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "Dockerfile build/"
        target: "/home/basudev/website"
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          ls -a
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD}}
        port: ${{ secrets.PORT}}
